### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by ksan27** [ksan27/furima-32053#9]
#URL
https://furima-32053.herokuapp.com/

#IDとパスワード
ID: admin
password: 2222

#出品者
Email: sample@sample.com
password: aaa111

#購入者
Email: sample2@sample.com
password: aaa111

#テストクレジットカード情報
番号: 42424242424242
期限: 3/24
コード: 123

**Comment by mutorisa** [comment]
ksan27さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきていますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
